### environments
@base = {{host}}/department

############################################################
### 1. 부서 전체 조회
############################################################
GET {{base}}/list
Accept: application/json