### environments
@base = {{host}}/doctor

############################################################
### 1. 부서별 의사 전체 조회
############################################################
GET {{base}}/list/department/1
Accept: application/json

############################################################
### 2. 의사별 공지사항 전체 조회
############################################################
GET {{base}}/3/notices
Accept: application/json