### environments
@base = {{host}}/reservation

############################################################
### 1. 날짜별 예약 가능 시간 조회
############################################################
GET {{base}}/doctor/1/available-times?date=2025-11-20
Accept: application/json

############################################################
### 2. 예약 생성
############################################################
POST {{base}}
Content-Type: application/json
Accept: application/json
Cookie: {{cookie}}

{
  "doctorId": 1,
  "reservationTime": "2025-11-20T09:30:00"
}

############################################################
### 3. 예약 단건 조회
############################################################
GET {{base}}/82
Accept: application/json
Cookie: {{cookie}}