### environments
@base = {{host}}/symptoms

############################################################
### 1. 증상 조회
############################################################
GET {{base}}
Accept: application/json